### PR TITLE
Refactor command

### PR DESCRIPTION
**Pull request by favrik**
Hello!,

this is an initial stab at #2.  Let me know if you have any thoughts/questions.

Comments:
- It should be easy to modify the breach data to sort breaches by date before rendering the table.
- The rate limit might be a deterrent to use the cli interface, not sure.
- Removed the call to `ProgressBar->setMessage()` as it wasn't doing anything; a custom format should be used to take advantage of it.
- To make things simpler, the duplicate check could be removed and assume that the input does not contain duplicate account identifiers.
- Idea: make the command be able to accept an account identifier in addition to a CSV file path.

Thanks!

### CODE REVIEW

**Comment by veloxy** [comment]
I was initially thinking about splitting it up 3 three parts/services. One being the source reader, the other being the processor and the third being the renderer. 

That would allow loading from different sources like Excel files/JSON/.. and also render the output different like generating an html report of something.

Either way, it's already looking much better than it initially was!

**Comment by favrik** [comment]
I only thought about adding the HaveIBeenPwned part as a service, but didn't want to go too far on this issue.    I think what you are describing depends heavily on the ultimate roadmap and use cases you have for this project.

Anyway, hope it helped.  Participating on this issue was a quick fun for me, mostly because I found out (and/or remembered) my account was compromised in a few sites.  :)

**Comment by veloxy** [comment]
I've tested it out, seems you've changed the command to run from `php console.php check:csv example.csv` to `php console.php example.csv`. Could you update the readme to reflect those changes? Then It's good to merge!

**Comment by favrik** [comment]
Done.  Thanks! :)

**Comment by veloxy** [comment]
Merged, thanks 👍

**Pull request merged**
